/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    exhibitions: Exhibition;
    'crazy-deals': CrazyDeal;
    'discount-coupons': DiscountCoupon;
    'blog-posts': BlogPost;
    'featured-brands': FeaturedBrand;
    'checklist-profiles': ChecklistProfile;
    'checklist-categories': ChecklistCategory;
    subscribers: Subscriber;
    'contact-inquiries': ContactInquiry;
    'exhibitor-inquiries': ExhibitorInquiry;
    'hidden-pages': HiddenPage;
    'promotional-popups': PromotionalPopup;
    'user-sessions': UserSession;
    'chat-conversations': ChatConversation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    exhibitions: ExhibitionsSelect<false> | ExhibitionsSelect<true>;
    'crazy-deals': CrazyDealsSelect<false> | CrazyDealsSelect<true>;
    'discount-coupons': DiscountCouponsSelect<false> | DiscountCouponsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'featured-brands': FeaturedBrandsSelect<false> | FeaturedBrandsSelect<true>;
    'checklist-profiles': ChecklistProfilesSelect<false> | ChecklistProfilesSelect<true>;
    'checklist-categories': ChecklistCategoriesSelect<false> | ChecklistCategoriesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'contact-inquiries': ContactInquiriesSelect<false> | ContactInquiriesSelect<true>;
    'exhibitor-inquiries': ExhibitorInquiriesSelect<false> | ExhibitorInquiriesSelect<true>;
    'hidden-pages': HiddenPagesSelect<false> | HiddenPagesSelect<true>;
    'promotional-popups': PromotionalPopupsSelect<false> | PromotionalPopupsSelect<true>;
    'user-sessions': UserSessionsSelect<false> | UserSessionsSelect<true>;
    'chat-conversations': ChatConversationsSelect<false> | ChatConversationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions".
 */
export interface Exhibition {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startDate: string;
  endDate: string;
  venue: string;
  state:
    | 'Johor'
    | 'Kedah'
    | 'Kelantan'
    | 'Kuala Lumpur'
    | 'Labuan'
    | 'Melaka'
    | 'Negeri Sembilan'
    | 'Pahang'
    | 'Penang'
    | 'Perak'
    | 'Perlis'
    | 'Putrajaya'
    | 'Sabah'
    | 'Sarawak'
    | 'Selangor'
    | 'Terengganu';
  bannerImage: number | Media;
  verticalVideo?: (number | null) | Media;
  floorplanImage?: (number | null) | Media;
  brandCount?: number | null;
  isUpcoming?: boolean | null;
  countdownEnabled?: boolean | null;
  /**
   * Google Maps link to venue
   */
  mapLink?: string | null;
  /**
   * Link to TNC hidden page (upload 1-2 weeks before event)
   */
  tncPage?: (number | null) | HiddenPage;
  /**
   * Contest section (e.g. Colouring Contest)
   */
  contest?: {
    enabled?: boolean | null;
    /**
     * e.g. Colouring Contest
     */
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Custom form fields as JSON array
     */
    formFields?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Share & Win section
   */
  shareAndWin?: {
    enabled?: boolean | null;
    title?: string | null;
    description?: string | null;
    hiddenPage?: (number | null) | HiddenPage;
  };
  programSchedule?:
    | {
        time: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hidden-pages".
 */
export interface HiddenPage {
  id: number;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'tnc' | 'contest' | 'crazy-deals' | 'share-win' | 'other';
  exhibition?: (number | null) | Exhibition;
  isPublished?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crazy-deals".
 */
export interface CrazyDeal {
  id: number;
  title: string;
  exhibition: number | Exhibition;
  description?: string | null;
  image: number | Media;
  originalPrice?: number | null;
  dealPrice?: number | null;
  brand?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-coupons".
 */
export interface DiscountCoupon {
  id: number;
  title: string;
  exhibition: number | Exhibition;
  description?: string | null;
  image?: (number | null) | Media;
  code?: string | null;
  validUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage: number | Media;
  category: 'home-tips' | 'trends-ideas' | 'buying-guide' | 'renovation' | 'interior-design' | 'smart-home';
  author?: string | null;
  publishedAt: string;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-brands".
 */
export interface FeaturedBrand {
  id: number;
  name: string;
  logo: number | Media;
  exhibition?: (number | null) | Exhibition;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklist-profiles".
 */
export interface ChecklistProfile {
  id: number;
  name: string;
  profileSlug: 'first-home' | 'home-renovation' | 'rental-airbnb';
  description: string;
  /**
   * Comma-separated top priority items
   */
  topPriorities?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklist-categories".
 */
export interface ChecklistCategory {
  id: number;
  profile: number | ChecklistProfile;
  /**
   * e.g. Living Room, Bedroom, Kitchen
   */
  room: string;
  items: {
    label: string;
    order?: number | null;
    id?: string | null;
  }[];
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  name: string;
  phone: string;
  email: string;
  state:
    | 'Johor'
    | 'Kedah'
    | 'Kelantan'
    | 'Kuala Lumpur'
    | 'Labuan'
    | 'Melaka'
    | 'Negeri Sembilan'
    | 'Pahang'
    | 'Penang'
    | 'Perak'
    | 'Perlis'
    | 'Putrajaya'
    | 'Sabah'
    | 'Sarawak'
    | 'Selangor'
    | 'Terengganu';
  source: 'newsletter' | 'event' | 'contact' | 'exhibitor';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries".
 */
export interface ContactInquiry {
  id: number;
  name: string;
  email: string;
  phone: string;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitor-inquiries".
 */
export interface ExhibitorInquiry {
  id: number;
  email: string;
  phone: string;
  exhibitVenue: string;
  companyName: string;
  productService: string;
  additionalInfo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotional-popups".
 */
export interface PromotionalPopup {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  ctaText?: string | null;
  ctaLink?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-sessions".
 */
export interface UserSession {
  id: number;
  sessionId: string;
  /**
   * Array of CrazyDeal IDs
   */
  favourites?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Checklist item ID -> checked state
   */
  checklistSelections?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  checklistProfile?: ('first-home' | 'home-renovation' | 'rental-airbnb') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-conversations".
 */
export interface ChatConversation {
  id: number;
  sessionId: string;
  /**
   * Array of {role, content, timestamp}
   */
  messages:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Captured visitor name
   */
  leadName?: string | null;
  /**
   * Captured visitor email
   */
  leadEmail?: string | null;
  /**
   * Captured visitor phone
   */
  leadPhone?: string | null;
  leadCaptured?: boolean | null;
  topic?: ('general' | 'exhibition' | 'exhibitor' | 'home-tips' | 'checklist' | 'other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'exhibitions';
        value: number | Exhibition;
      } | null)
    | ({
        relationTo: 'crazy-deals';
        value: number | CrazyDeal;
      } | null)
    | ({
        relationTo: 'discount-coupons';
        value: number | DiscountCoupon;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'featured-brands';
        value: number | FeaturedBrand;
      } | null)
    | ({
        relationTo: 'checklist-profiles';
        value: number | ChecklistProfile;
      } | null)
    | ({
        relationTo: 'checklist-categories';
        value: number | ChecklistCategory;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'contact-inquiries';
        value: number | ContactInquiry;
      } | null)
    | ({
        relationTo: 'exhibitor-inquiries';
        value: number | ExhibitorInquiry;
      } | null)
    | ({
        relationTo: 'hidden-pages';
        value: number | HiddenPage;
      } | null)
    | ({
        relationTo: 'promotional-popups';
        value: number | PromotionalPopup;
      } | null)
    | ({
        relationTo: 'user-sessions';
        value: number | UserSession;
      } | null)
    | ({
        relationTo: 'chat-conversations';
        value: number | ChatConversation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions_select".
 */
export interface ExhibitionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  venue?: T;
  state?: T;
  bannerImage?: T;
  verticalVideo?: T;
  floorplanImage?: T;
  brandCount?: T;
  isUpcoming?: T;
  countdownEnabled?: T;
  mapLink?: T;
  tncPage?: T;
  contest?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
        image?: T;
        formFields?: T;
      };
  shareAndWin?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
        hiddenPage?: T;
      };
  programSchedule?:
    | T
    | {
        time?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crazy-deals_select".
 */
export interface CrazyDealsSelect<T extends boolean = true> {
  title?: T;
  exhibition?: T;
  description?: T;
  image?: T;
  originalPrice?: T;
  dealPrice?: T;
  brand?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-coupons_select".
 */
export interface DiscountCouponsSelect<T extends boolean = true> {
  title?: T;
  exhibition?: T;
  description?: T;
  image?: T;
  code?: T;
  validUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-brands_select".
 */
export interface FeaturedBrandsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  exhibition?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklist-profiles_select".
 */
export interface ChecklistProfilesSelect<T extends boolean = true> {
  name?: T;
  profileSlug?: T;
  description?: T;
  topPriorities?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklist-categories_select".
 */
export interface ChecklistCategoriesSelect<T extends boolean = true> {
  profile?: T;
  room?: T;
  items?:
    | T
    | {
        label?: T;
        order?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  state?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries_select".
 */
export interface ContactInquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitor-inquiries_select".
 */
export interface ExhibitorInquiriesSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  exhibitVenue?: T;
  companyName?: T;
  productService?: T;
  additionalInfo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hidden-pages_select".
 */
export interface HiddenPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  type?: T;
  exhibition?: T;
  isPublished?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotional-popups_select".
 */
export interface PromotionalPopupsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  image?: T;
  ctaText?: T;
  ctaLink?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-sessions_select".
 */
export interface UserSessionsSelect<T extends boolean = true> {
  sessionId?: T;
  favourites?: T;
  checklistSelections?: T;
  checklistProfile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-conversations_select".
 */
export interface ChatConversationsSelect<T extends boolean = true> {
  sessionId?: T;
  messages?: T;
  leadName?: T;
  leadEmail?: T;
  leadPhone?: T;
  leadCaptured?: T;
  topic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}